git:
  depth: 1

dist: 
  trusty

language: java

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - chmod +x mvnw